--SELECIONANDO TODOS REGISTROS DA TABELA
SELECT	
	[ID], 
	[NOME], 
	[TELEFONE]
FROM 
	[TBContato]
--SELECIONANDO APENAS UM REGISTRO DA TABELA
SELECT 
	[ID],
	[NOME],
	[TELEFONE]
FROM 
	[TBContato]
WHERE 
	[ID] = 8

--INSERINDO REGISTROS NA TABELA

INSERT INTO [TBContato]
VALUES (
		'CHARLES JUNIOR',
		'49 999400611'
		);
--SELECIONAR O ULTIMO ID
SELECT SCOPE_IDENTITY ();

-- EXCLUIR UM REGISTRO DA TABELA
DELETE FROM [TBContato]
	WHERE [ID] = 5
--ATUALIZANDO TODOS OS REGISTROS DA TABELA
UPDATE	[TBContato]
	SET 
		[NOME] = 'Jéssica Alves',
		[TELEFONE] =  '49 99999999'
	WHERE 
		[ID] = 7



